#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $DB_NAME_GOPHERMART;
    CREATE DATABASE $DB_NAME_ACCRUAL;

    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME_GOPHERMART TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME_ACCRUAL TO $POSTGRES_USER;
EOSQL
