// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCookieService creates a new instance of MockCookieService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCookieService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCookieService {
	mock := &MockCookieService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCookieService is an autogenerated mock type for the CookieService type
type MockCookieService struct {
	mock.Mock
}

type MockCookieService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCookieService) EXPECT() *MockCookieService_Expecter {
	return &MockCookieService_Expecter{mock: &_m.Mock}
}

// GetAuthToken provides a mock function for the type MockCookieService
func (_mock *MockCookieService) GetAuthToken(r *http.Request) (string, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (string, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCookieService_GetAuthToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthToken'
type MockCookieService_GetAuthToken_Call struct {
	*mock.Call
}

// GetAuthToken is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockCookieService_Expecter) GetAuthToken(r interface{}) *MockCookieService_GetAuthToken_Call {
	return &MockCookieService_GetAuthToken_Call{Call: _e.mock.On("GetAuthToken", r)}
}

func (_c *MockCookieService_GetAuthToken_Call) Run(run func(r *http.Request)) *MockCookieService_GetAuthToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCookieService_GetAuthToken_Call) Return(s string, err error) *MockCookieService_GetAuthToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCookieService_GetAuthToken_Call) RunAndReturn(run func(r *http.Request) (string, error)) *MockCookieService_GetAuthToken_Call {
	_c.Call.Return(run)
	return _c
}
