dir: "{{.InterfaceDir}}"
filename: "mock_{{ .InterfaceName | snakecase }}.gen.go"
pkgname: '{{.SrcPackageName}}'
structname: '{{.Mock}}{{.InterfaceName}}'
template: testify
packages:
  github.com/liebeSonne/gophermart/internal/repository:
    interfaces:
      UserRepository: { }
      UserOrderRepository: { }
      UserBalanceRepository: {}
      UserBalanceWithdrawnRepository: {}
  github.com/liebeSonne/gophermart/internal/repository/uow:
    interfaces:
      UnitOfWorkFactory: {}
      RepositoryProvider: {}
  github.com/liebeSonne/gophermart/internal/provider:
    interfaces:
      UserProvider: { }
      UserOrderProvider: { }
  github.com/liebeSonne/gophermart/internal/service:
    interfaces:
      UserService: { }
      PasswordService: { }
      AccrualService: {}
  github.com/liebeSonne/gophermart/internal/service/async:
    interfaces:
      Producer: {}
  github.com/liebeSonne/gophermart/internal/auth:
    interfaces:
      TokenService: { }
  github.com/liebeSonne/gophermart/internal/handler/cookie:
    interfaces:
      Service: { }
  github.com/liebeSonne/gophermart/internal/adapter:
    interfaces:
      AccrualClientWithResponsesInterface: {}
