dir: "{{.InterfaceDir}}"
filename: "mock_{{ .InterfaceName | snakecase }}.gen.go"
pkgname: '{{.SrcPackageName}}'
structname: '{{.Mock}}{{.InterfaceName}}'
template: testify
packages:
  github.com/liebeSonne/gophermart/internal/service:
    interfaces:
      PasswordService: { }
      AccrualService: {}
      UnitOfWorkFactory: { }
      RepositoryProvider: { }
      UserRepository: { }
      UserOrderRepository: { }
      UserBalanceRepository: { }
      UserBalanceWithdrawnRepository: { }
      UserProvider: { }
      UserOrderProvider: { }
      ExecutedUserOrderProvider: {}
  github.com/liebeSonne/gophermart/internal/service/async:
    interfaces:
      Producer: {}
  github.com/liebeSonne/gophermart/internal/handler/auth:
    interfaces:
      TokenService: { }
      CookieService: { }
  github.com/liebeSonne/gophermart/internal/adapter:
    interfaces:
      AccrualClientWithResponsesInterface: {}
  github.com/liebeSonne/gophermart/internal/repository:
    interfaces:
      ContextClient: {}
  github.com/liebeSonne/gophermart/internal/repository/database:
    interfaces:
      Rows: {}
      Row: {}
