// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package client

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for GetOrdersResponseDataStatus.
const (
	INVALID    GetOrdersResponseDataStatus = "INVALID"
	PROCESSED  GetOrdersResponseDataStatus = "PROCESSED"
	PROCESSING GetOrdersResponseDataStatus = "PROCESSING"
	REGISTERED GetOrdersResponseDataStatus = "REGISTERED"
)

// Valid indicates whether the value is a known member of the GetOrdersResponseDataStatus enum.
func (e GetOrdersResponseDataStatus) Valid() bool {
	switch e {
	case INVALID:
		return true
	case PROCESSED:
		return true
	case PROCESSING:
		return true
	case REGISTERED:
		return true
	default:
		return false
	}
}

// GetOrdersResponseData defines model for GetOrdersResponseData.
type GetOrdersResponseData struct {
	// Accrual рассчитанные баллы к начислению, при отсутствии начисления (status не равен PROCESSED)— поле отсутствует в ответе
	Accrual *float32 `json:"accrual,omitempty"`

	// Order номер заказа
	Order string `json:"order"`

	// Status статус расчёта начисления
	Status GetOrdersResponseDataStatus `json:"status"`
}

// GetOrdersResponseDataStatus статус расчёта начисления
type GetOrdersResponseDataStatus string

// OrdersGoodData defines model for OrdersGoodData.
type OrdersGoodData struct {
	// Description наименование товара
	Description string `json:"description"`

	// Price цена оплаченного товара
	Price float32 `json:"price"`
}

// PostGoodsRequestData defines model for PostGoodsRequestData.
type PostGoodsRequestData struct {
	// Match ключ поиска (проверяется на наличие в строке наименования товара), не может быть пустым
	Match string `json:"match"`

	// Reward размер вознаграждения
	Reward float32 `json:"reward"`

	// RewardType тип вознаграждения ('%' - процент от стоимости товара; 'pt' - точное количество баллов)
	RewardType string `json:"reward_type"`
}

// PostOrdersRequestData defines model for PostOrdersRequestData.
type PostOrdersRequestData struct {
	// Goods список купленных товаров
	Goods []OrdersGoodData `json:"goods"`

	// Order номер заказа
	Order string `json:"order"`
}

// PostGoodsJSONRequestBody defines body for PostGoods for application/json ContentType.
type PostGoodsJSONRequestBody = PostGoodsRequestData

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody = PostOrdersRequestData

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostGoodsWithBody request with any body
	PostGoodsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostGoods(ctx context.Context, body PostGoodsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostOrdersWithBody request with any body
	PostOrdersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOrders(ctx context.Context, body PostOrdersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOrders request
	GetOrders(ctx context.Context, number string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostGoodsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostGoodsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostGoods(ctx context.Context, body PostGoodsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostGoodsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOrdersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOrdersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOrders(ctx context.Context, body PostOrdersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOrdersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOrders(ctx context.Context, number string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOrdersRequest(c.Server, number)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostGoodsRequest calls the generic PostGoods builder with application/json body
func NewPostGoodsRequest(server string, body PostGoodsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostGoodsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostGoodsRequestWithBody generates requests for PostGoods with any type of body
func NewPostGoodsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/goods")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostOrdersRequest calls the generic PostOrders builder with application/json body
func NewPostOrdersRequest(server string, body PostOrdersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostOrdersRequestWithBody(server, "application/json", bodyReader)
}

// NewPostOrdersRequestWithBody generates requests for PostOrders with any type of body
func NewPostOrdersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/orders")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetOrdersRequest generates requests for GetOrders
func NewGetOrdersRequest(server string, number string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "number", number, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/orders/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostGoodsWithBodyWithResponse request with any body
	PostGoodsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostGoodsResponse, error)

	PostGoodsWithResponse(ctx context.Context, body PostGoodsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostGoodsResponse, error)

	// PostOrdersWithBodyWithResponse request with any body
	PostOrdersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOrdersResponse, error)

	PostOrdersWithResponse(ctx context.Context, body PostOrdersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOrdersResponse, error)

	// GetOrdersWithResponse request
	GetOrdersWithResponse(ctx context.Context, number string, reqEditors ...RequestEditorFn) (*GetOrdersResponse, error)
}

type PostGoodsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostGoodsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostGoodsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostGoodsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostOrdersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostOrdersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOrdersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostOrdersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetOrdersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetOrdersResponseData
}

// Status returns HTTPResponse.Status
func (r GetOrdersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOrdersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOrdersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostGoodsWithBodyWithResponse request with arbitrary body returning *PostGoodsResponse
func (c *ClientWithResponses) PostGoodsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostGoodsResponse, error) {
	rsp, err := c.PostGoodsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostGoodsResponse(rsp)
}

func (c *ClientWithResponses) PostGoodsWithResponse(ctx context.Context, body PostGoodsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostGoodsResponse, error) {
	rsp, err := c.PostGoods(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostGoodsResponse(rsp)
}

// PostOrdersWithBodyWithResponse request with arbitrary body returning *PostOrdersResponse
func (c *ClientWithResponses) PostOrdersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOrdersResponse, error) {
	rsp, err := c.PostOrdersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOrdersResponse(rsp)
}

func (c *ClientWithResponses) PostOrdersWithResponse(ctx context.Context, body PostOrdersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostOrdersResponse, error) {
	rsp, err := c.PostOrders(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOrdersResponse(rsp)
}

// GetOrdersWithResponse request returning *GetOrdersResponse
func (c *ClientWithResponses) GetOrdersWithResponse(ctx context.Context, number string, reqEditors ...RequestEditorFn) (*GetOrdersResponse, error) {
	rsp, err := c.GetOrders(ctx, number, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOrdersResponse(rsp)
}

// ParsePostGoodsResponse parses an HTTP response from a PostGoodsWithResponse call
func ParsePostGoodsResponse(rsp *http.Response) (*PostGoodsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostGoodsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostOrdersResponse parses an HTTP response from a PostOrdersWithResponse call
func ParsePostOrdersResponse(rsp *http.Response) (*PostOrdersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOrdersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetOrdersResponse parses an HTTP response from a GetOrdersWithResponse call
func ParseGetOrdersResponse(rsp *http.Response) (*GetOrdersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOrdersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetOrdersResponseData
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFfdbhNHFH6V0bQVIC3YSaEC9yptoigSBRRQbxCqBnsSL/L+dHYMRJGl2G5JpCAipN63j+CYLFnsePMK",
	"Z16hT1KdMxvba68TLqA3iXd2Z+ac73znm292eTXwwsCXvo54ZZcrGYWBH0l6eBIEvwh/Z1P+3pSRfV8N",
	"fC19jT+1fK1LYUO4Pj5F1br0BP6Sr4UXNiSv8AcB8wIlma4Lny2Vy0xlK7FQKua5flNLJhqN4JWscYfr",
	"nRBnRVq5/jZvtVoOr8moqtxQu4HPKxzOzR7E0DeH5gBiGEHKYAApDCEx+xCbtulAHwdPoUffpqYNKfQZ",
	"DJhpQ2z2oA+JaZsud3hdippUlNSm1Grn5sqWlgofZzYt2gFXg4HpwghOHArCdCDFHSFmMDJd+GjDO4cU",
	"TiCFj3ACPdMxb3EopjRO7Nt+NnNkDuFsNvQz7hQi+0N5gpfra7ktFQKGkNnPKa91qR8qTHIzq+qq0LRQ",
	"qIJQKu3aMotqVTVFYz51swc90zZtsw+J6UAPRhRlzOAYejCEoTlEaGEEPfqkDUMqS2LeOYyySBgig4jT",
	"XwQvwcH5GUfseqSFbkb4Mma4NfTxHXu0+fDntceP11Zv/Lv3l8VsiDHMLGy6EJsOw2qntFFsOhBzZwq1",
	"pfKt8h3u8K1AeULzCt9qBEJPkPSb3nME0uEBwlbAhRHWBOtnCzWAHv6f567DbTIFmGKwyISuabMM4H3z",
	"HgcLYcEE/KbHK0/55tr6xuMna5trq9zhGw9+Xbm/gb8yfDYerE8e1lb5s/mGcjg2oKtkDZezOY4jnXwf",
	"PH8hqxqTsOxZD4JaMXNyqRWA1YME4SLY+sSfBGvbsY+YfRF0oXKrsgC5N7RSj0EK5zAkqHAAF/+APZlf",
	"9qoiz6BhN80rThEkj4JIIyBRporFwHhCV+uFWjI078y+ZTHWeQA9dt02PFF2zxwhcU3bHDGb7IhaDeUH",
	"sYM+QwbR9wPSmiKQzVEOjRuObSo4IyWiNjk2h5kcIRNNB9WHO9xz/fvS39Z1XlkqKI2Sr4SqFSsFnF60",
	"Rh9SOKXIPtALFL8Jna/uPrvLb3Z8bqsOJHB+6Sbs+rXvrrGbLBNS4g3mnJoOoYfYIxb0O8lB9SO7Fmqc",
	"S6q8T6DGC06ZTARx8g1+VbdZRowRzCe5iGgX6n0J07aRi0UyA+dEsBQFGk+q80xTRubQ/Dmdcwp97nBX",
	"S4/W+VbJLV7h35QmxqCUnSmlGT1ojcMWSomdLyGcCzTKZjkPE37v+lsB+RFXk8qv2OOMRTuRlh5bebTB",
	"Hf5SqsiGsnSrfKtMoYbSF6HLK/x7GnJ4KHSdMCiJ0C2NkQ2DiAwPwi4woY0ar0yEgNuQZaR/Cmo7MyZJ",
	"hGHDrdKs0osomLFKl2FdKDStPEBaNSUNTJm25XK5AP+F3YJ63CW2xObAepZTokUMH8grodYkmT6huKSI",
	"3e3CTUZozsjdoE34xMwf5GzO8LzLO5ueXeTe50okGar4itBwzTsLsh+RUdjLOuAI1TU1B5DAsV3/wh3G",
	"dHqQj2p6nlA7OP2f3I4984ZEBhIYTWX4xjqb9BJlwvenuNu4+WgnYhsx/Qq62fb7inyb15vPItxyAeTj",
	"Lp+jF/lCKkLm1uCYYDom3zYw3a9MsOnILKs+K6L/k1n2KM9sTXtsDQ7M+ym/kxPSGR6Vdu1p2qIjQhbw",
	"aXw3IN1TwpOa+Pd0l+OFjrSQO9wX3tTZPEuF6cvJrJA/K9alL8LV4otNwY0xx70e1SZfW3RYc7xZLt++",
	"lDfWTF2qRdao2TcQ49E3Nvt0MbH8XL63KNMxdKXZS/jXouLfaHFMNzPV5DUXCFzu1hIX3FrgU84cMfxn",
	"jmBo3iJ5reuy1YqkenlBu6Zq8Aqvax1WSqVGUBWNehDpyt3y3SXeetb6LwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
