// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package adapter

import (
	"context"

	"github.com/liebeSonne/gophermart/api/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccrualClientWithResponsesInterface creates a new instance of MockAccrualClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrualClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrualClientWithResponsesInterface {
	mock := &MockAccrualClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccrualClientWithResponsesInterface is an autogenerated mock type for the AccrualClientWithResponsesInterface type
type MockAccrualClientWithResponsesInterface struct {
	mock.Mock
}

type MockAccrualClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrualClientWithResponsesInterface) EXPECT() *MockAccrualClientWithResponsesInterface_Expecter {
	return &MockAccrualClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// GetOrdersWithResponse provides a mock function for the type MockAccrualClientWithResponsesInterface
func (_mock *MockAccrualClientWithResponsesInterface) GetOrdersWithResponse(ctx context.Context, number string, reqEditors ...client.RequestEditorFn) (*client.GetOrdersResponse, error) {
	var tmpRet mock.Arguments
	if len(reqEditors) > 0 {
		tmpRet = _mock.Called(ctx, number, reqEditors)
	} else {
		tmpRet = _mock.Called(ctx, number)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersWithResponse")
	}

	var r0 *client.GetOrdersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) (*client.GetOrdersResponse, error)); ok {
		return returnFunc(ctx, number, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.RequestEditorFn) *client.GetOrdersResponse); ok {
		r0 = returnFunc(ctx, number, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetOrdersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, number, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccrualClientWithResponsesInterface_GetOrdersWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersWithResponse'
type MockAccrualClientWithResponsesInterface_GetOrdersWithResponse_Call struct {
	*mock.Call
}

// GetOrdersWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
//   - reqEditors ...client.RequestEditorFn
func (_e *MockAccrualClientWithResponsesInterface_Expecter) GetOrdersWithResponse(ctx interface{}, number interface{}, reqEditors ...interface{}) *MockAccrualClientWithResponsesInterface_GetOrdersWithResponse_Call {
	return &MockAccrualClientWithResponsesInterface_GetOrdersWithResponse_Call{Call: _e.mock.On("GetOrdersWithResponse",
		append([]interface{}{ctx, number}, reqEditors...)...)}
}

func (_c *MockAccrualClientWithResponsesInterface_GetOrdersWithResponse_Call) Run(run func(ctx context.Context, number string, reqEditors ...client.RequestEditorFn)) *MockAccrualClientWithResponsesInterface_GetOrdersWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.RequestEditorFn
		var variadicArgs []client.RequestEditorFn
		if len(args) > 2 {
			variadicArgs = args[2].([]client.RequestEditorFn)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAccrualClientWithResponsesInterface_GetOrdersWithResponse_Call) Return(getOrdersResponse *client.GetOrdersResponse, err error) *MockAccrualClientWithResponsesInterface_GetOrdersWithResponse_Call {
	_c.Call.Return(getOrdersResponse, err)
	return _c
}

func (_c *MockAccrualClientWithResponsesInterface_GetOrdersWithResponse_Call) RunAndReturn(run func(ctx context.Context, number string, reqEditors ...client.RequestEditorFn) (*client.GetOrdersResponse, error)) *MockAccrualClientWithResponsesInterface_GetOrdersWithResponse_Call {
	_c.Call.Return(run)
	return _c
}
