// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserBalanceService creates a new instance of MockUserBalanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserBalanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserBalanceService {
	mock := &MockUserBalanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserBalanceService is an autogenerated mock type for the UserBalanceService type
type MockUserBalanceService struct {
	mock.Mock
}

type MockUserBalanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserBalanceService) EXPECT() *MockUserBalanceService_Expecter {
	return &MockUserBalanceService_Expecter{mock: &_m.Mock}
}

// AddWithdrawn provides a mock function for the type MockUserBalanceService
func (_mock *MockUserBalanceService) AddWithdrawn(ctx context.Context, input AddWithdrawnInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AddWithdrawn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AddWithdrawnInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserBalanceService_AddWithdrawn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWithdrawn'
type MockUserBalanceService_AddWithdrawn_Call struct {
	*mock.Call
}

// AddWithdrawn is a helper method to define mock.On call
//   - ctx context.Context
//   - input AddWithdrawnInput
func (_e *MockUserBalanceService_Expecter) AddWithdrawn(ctx interface{}, input interface{}) *MockUserBalanceService_AddWithdrawn_Call {
	return &MockUserBalanceService_AddWithdrawn_Call{Call: _e.mock.On("AddWithdrawn", ctx, input)}
}

func (_c *MockUserBalanceService_AddWithdrawn_Call) Run(run func(ctx context.Context, input AddWithdrawnInput)) *MockUserBalanceService_AddWithdrawn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AddWithdrawnInput
		if args[1] != nil {
			arg1 = args[1].(AddWithdrawnInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserBalanceService_AddWithdrawn_Call) Return(err error) *MockUserBalanceService_AddWithdrawn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserBalanceService_AddWithdrawn_Call) RunAndReturn(run func(ctx context.Context, input AddWithdrawnInput) error) *MockUserBalanceService_AddWithdrawn_Call {
	_c.Call.Return(run)
	return _c
}
