// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/liebeSonne/gophermart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserOrderService creates a new instance of MockUserOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserOrderService {
	mock := &MockUserOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserOrderService is an autogenerated mock type for the UserOrderService type
type MockUserOrderService struct {
	mock.Mock
}

type MockUserOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserOrderService) EXPECT() *MockUserOrderService_Expecter {
	return &MockUserOrderService_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function for the type MockUserOrderService
func (_mock *MockUserOrderService) Upload(ctx context.Context, input UploadUserOrderInput) (model.UserOrder, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 model.UserOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UploadUserOrderInput) (model.UserOrder, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, UploadUserOrderInput) model.UserOrder); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(model.UserOrder)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, UploadUserOrderInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserOrderService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockUserOrderService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - input UploadUserOrderInput
func (_e *MockUserOrderService_Expecter) Upload(ctx interface{}, input interface{}) *MockUserOrderService_Upload_Call {
	return &MockUserOrderService_Upload_Call{Call: _e.mock.On("Upload", ctx, input)}
}

func (_c *MockUserOrderService_Upload_Call) Run(run func(ctx context.Context, input UploadUserOrderInput)) *MockUserOrderService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UploadUserOrderInput
		if args[1] != nil {
			arg1 = args[1].(UploadUserOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserOrderService_Upload_Call) Return(userOrder model.UserOrder, err error) *MockUserOrderService_Upload_Call {
	_c.Call.Return(userOrder, err)
	return _c
}

func (_c *MockUserOrderService_Upload_Call) RunAndReturn(run func(ctx context.Context, input UploadUserOrderInput) (model.UserOrder, error)) *MockUserOrderService_Upload_Call {
	_c.Call.Return(run)
	return _c
}
