// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophermart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserBalanceQueryService creates a new instance of MockUserBalanceQueryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserBalanceQueryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserBalanceQueryService {
	mock := &MockUserBalanceQueryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserBalanceQueryService is an autogenerated mock type for the UserBalanceQueryService type
type MockUserBalanceQueryService struct {
	mock.Mock
}

type MockUserBalanceQueryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserBalanceQueryService) EXPECT() *MockUserBalanceQueryService_Expecter {
	return &MockUserBalanceQueryService_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function for the type MockUserBalanceQueryService
func (_mock *MockUserBalanceQueryService) GetByUserID(ctx context.Context, userID uuid.UUID) (model.UserBalance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 model.UserBalance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.UserBalance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.UserBalance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.UserBalance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceQueryService_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockUserBalanceQueryService_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserBalanceQueryService_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockUserBalanceQueryService_GetByUserID_Call {
	return &MockUserBalanceQueryService_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockUserBalanceQueryService_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserBalanceQueryService_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserBalanceQueryService_GetByUserID_Call) Return(userBalance model.UserBalance, err error) *MockUserBalanceQueryService_GetByUserID_Call {
	_c.Call.Return(userBalance, err)
	return _c
}

func (_c *MockUserBalanceQueryService_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (model.UserBalance, error)) *MockUserBalanceQueryService_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}
