// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCookieService creates a new instance of MockCookieService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCookieService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCookieService {
	mock := &MockCookieService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCookieService is an autogenerated mock type for the CookieService type
type MockCookieService struct {
	mock.Mock
}

type MockCookieService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCookieService) EXPECT() *MockCookieService_Expecter {
	return &MockCookieService_Expecter{mock: &_m.Mock}
}

// SetAuthToken provides a mock function for the type MockCookieService
func (_mock *MockCookieService) SetAuthToken(tokenString string, w http.ResponseWriter, r *http.Request) error {
	ret := _mock.Called(tokenString, w, r)

	if len(ret) == 0 {
		panic("no return value specified for SetAuthToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, http.ResponseWriter, *http.Request) error); ok {
		r0 = returnFunc(tokenString, w, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCookieService_SetAuthToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAuthToken'
type MockCookieService_SetAuthToken_Call struct {
	*mock.Call
}

// SetAuthToken is a helper method to define mock.On call
//   - tokenString string
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockCookieService_Expecter) SetAuthToken(tokenString interface{}, w interface{}, r interface{}) *MockCookieService_SetAuthToken_Call {
	return &MockCookieService_SetAuthToken_Call{Call: _e.mock.On("SetAuthToken", tokenString, w, r)}
}

func (_c *MockCookieService_SetAuthToken_Call) Run(run func(tokenString string, w http.ResponseWriter, r *http.Request)) *MockCookieService_SetAuthToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 http.ResponseWriter
		if args[1] != nil {
			arg1 = args[1].(http.ResponseWriter)
		}
		var arg2 *http.Request
		if args[2] != nil {
			arg2 = args[2].(*http.Request)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCookieService_SetAuthToken_Call) Return(err error) *MockCookieService_SetAuthToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCookieService_SetAuthToken_Call) RunAndReturn(run func(tokenString string, w http.ResponseWriter, r *http.Request) error) *MockCookieService_SetAuthToken_Call {
	_c.Call.Return(run)
	return _c
}
