// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophermart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserOrderQueryService creates a new instance of MockUserOrderQueryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserOrderQueryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserOrderQueryService {
	mock := &MockUserOrderQueryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserOrderQueryService is an autogenerated mock type for the UserOrderQueryService type
type MockUserOrderQueryService struct {
	mock.Mock
}

type MockUserOrderQueryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserOrderQueryService) EXPECT() *MockUserOrderQueryService_Expecter {
	return &MockUserOrderQueryService_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function for the type MockUserOrderQueryService
func (_mock *MockUserOrderQueryService) FindByUserID(ctx context.Context, userID uuid.UUID) ([]model.UserOrder, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []model.UserOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.UserOrder, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.UserOrder); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserOrderQueryService_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockUserOrderQueryService_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserOrderQueryService_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockUserOrderQueryService_FindByUserID_Call {
	return &MockUserOrderQueryService_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockUserOrderQueryService_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserOrderQueryService_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserOrderQueryService_FindByUserID_Call) Return(userOrders []model.UserOrder, err error) *MockUserOrderQueryService_FindByUserID_Call {
	_c.Call.Return(userOrders, err)
	return _c
}

func (_c *MockUserOrderQueryService_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]model.UserOrder, error)) *MockUserOrderQueryService_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}
