// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophermart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserOrderRepository creates a new instance of MockUserOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserOrderRepository {
	mock := &MockUserOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserOrderRepository is an autogenerated mock type for the UserOrderRepository type
type MockUserOrderRepository struct {
	mock.Mock
}

type MockUserOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserOrderRepository) EXPECT() *MockUserOrderRepository_Expecter {
	return &MockUserOrderRepository_Expecter{mock: &_m.Mock}
}

// FindByOrderID provides a mock function for the type MockUserOrderRepository
func (_mock *MockUserOrderRepository) FindByOrderID(ctx context.Context, orderID string) (*model.UserOrder, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderID")
	}

	var r0 *model.UserOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.UserOrder, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.UserOrder); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserOrderRepository_FindByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrderID'
type MockUserOrderRepository_FindByOrderID_Call struct {
	*mock.Call
}

// FindByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockUserOrderRepository_Expecter) FindByOrderID(ctx interface{}, orderID interface{}) *MockUserOrderRepository_FindByOrderID_Call {
	return &MockUserOrderRepository_FindByOrderID_Call{Call: _e.mock.On("FindByOrderID", ctx, orderID)}
}

func (_c *MockUserOrderRepository_FindByOrderID_Call) Run(run func(ctx context.Context, orderID string)) *MockUserOrderRepository_FindByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserOrderRepository_FindByOrderID_Call) Return(userOrder *model.UserOrder, err error) *MockUserOrderRepository_FindByOrderID_Call {
	_c.Call.Return(userOrder, err)
	return _c
}

func (_c *MockUserOrderRepository_FindByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*model.UserOrder, error)) *MockUserOrderRepository_FindByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockUserOrderRepository
func (_mock *MockUserOrderRepository) FindByUserID(ctx context.Context, userID uuid.UUID) ([]model.UserOrder, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []model.UserOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.UserOrder, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.UserOrder); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserOrderRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockUserOrderRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserOrderRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockUserOrderRepository_FindByUserID_Call {
	return &MockUserOrderRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockUserOrderRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserOrderRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserOrderRepository_FindByUserID_Call) Return(userOrders []model.UserOrder, err error) *MockUserOrderRepository_FindByUserID_Call {
	_c.Call.Return(userOrders, err)
	return _c
}

func (_c *MockUserOrderRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]model.UserOrder, error)) *MockUserOrderRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NextID provides a mock function for the type MockUserOrderRepository
func (_mock *MockUserOrderRepository) NextID(ctx context.Context) uuid.UUID {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NextID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockUserOrderRepository_NextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextID'
type MockUserOrderRepository_NextID_Call struct {
	*mock.Call
}

// NextID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserOrderRepository_Expecter) NextID(ctx interface{}) *MockUserOrderRepository_NextID_Call {
	return &MockUserOrderRepository_NextID_Call{Call: _e.mock.On("NextID", ctx)}
}

func (_c *MockUserOrderRepository_NextID_Call) Run(run func(ctx context.Context)) *MockUserOrderRepository_NextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserOrderRepository_NextID_Call) Return(uUID uuid.UUID) *MockUserOrderRepository_NextID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockUserOrderRepository_NextID_Call) RunAndReturn(run func(ctx context.Context) uuid.UUID) *MockUserOrderRepository_NextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockUserOrderRepository
func (_mock *MockUserOrderRepository) Store(ctx context.Context, items []model.UserOrder) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.UserOrder) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserOrderRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockUserOrderRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - items []model.UserOrder
func (_e *MockUserOrderRepository_Expecter) Store(ctx interface{}, items interface{}) *MockUserOrderRepository_Store_Call {
	return &MockUserOrderRepository_Store_Call{Call: _e.mock.On("Store", ctx, items)}
}

func (_c *MockUserOrderRepository_Store_Call) Run(run func(ctx context.Context, items []model.UserOrder)) *MockUserOrderRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.UserOrder
		if args[1] != nil {
			arg1 = args[1].([]model.UserOrder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserOrderRepository_Store_Call) Return(err error) *MockUserOrderRepository_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserOrderRepository_Store_Call) RunAndReturn(run func(ctx context.Context, items []model.UserOrder) error) *MockUserOrderRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}
