// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophermart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserBalanceRepository creates a new instance of MockUserBalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserBalanceRepository {
	mock := &MockUserBalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserBalanceRepository is an autogenerated mock type for the UserBalanceRepository type
type MockUserBalanceRepository struct {
	mock.Mock
}

type MockUserBalanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserBalanceRepository) EXPECT() *MockUserBalanceRepository_Expecter {
	return &MockUserBalanceRepository_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function for the type MockUserBalanceRepository
func (_mock *MockUserBalanceRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (model.UserBalance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 model.UserBalance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.UserBalance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.UserBalance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.UserBalance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockUserBalanceRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserBalanceRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockUserBalanceRepository_GetByUserID_Call {
	return &MockUserBalanceRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockUserBalanceRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserBalanceRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserBalanceRepository_GetByUserID_Call) Return(userBalance model.UserBalance, err error) *MockUserBalanceRepository_GetByUserID_Call {
	_c.Call.Return(userBalance, err)
	return _c
}

func (_c *MockUserBalanceRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (model.UserBalance, error)) *MockUserBalanceRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockUserBalanceRepository
func (_mock *MockUserBalanceRepository) Store(ctx context.Context, item model.UserBalance) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserBalance) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserBalanceRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockUserBalanceRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - item model.UserBalance
func (_e *MockUserBalanceRepository_Expecter) Store(ctx interface{}, item interface{}) *MockUserBalanceRepository_Store_Call {
	return &MockUserBalanceRepository_Store_Call{Call: _e.mock.On("Store", ctx, item)}
}

func (_c *MockUserBalanceRepository_Store_Call) Run(run func(ctx context.Context, item model.UserBalance)) *MockUserBalanceRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserBalance
		if args[1] != nil {
			arg1 = args[1].(model.UserBalance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserBalanceRepository_Store_Call) Return(err error) *MockUserBalanceRepository_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserBalanceRepository_Store_Call) RunAndReturn(run func(ctx context.Context, item model.UserBalance) error) *MockUserBalanceRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}
