// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordService creates a new instance of MockPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordService {
	mock := &MockPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordService is an autogenerated mock type for the PasswordService type
type MockPasswordService struct {
	mock.Mock
}

type MockPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordService) EXPECT() *MockPasswordService_Expecter {
	return &MockPasswordService_Expecter{mock: &_m.Mock}
}

// CheckHash provides a mock function for the type MockPasswordService
func (_mock *MockPasswordService) CheckHash(ctx context.Context, password string, hash string) (bool, error) {
	ret := _mock.Called(ctx, password, hash)

	if len(ret) == 0 {
		panic("no return value specified for CheckHash")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, password, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, password, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordService_CheckHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHash'
type MockPasswordService_CheckHash_Call struct {
	*mock.Call
}

// CheckHash is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
//   - hash string
func (_e *MockPasswordService_Expecter) CheckHash(ctx interface{}, password interface{}, hash interface{}) *MockPasswordService_CheckHash_Call {
	return &MockPasswordService_CheckHash_Call{Call: _e.mock.On("CheckHash", ctx, password, hash)}
}

func (_c *MockPasswordService_CheckHash_Call) Run(run func(ctx context.Context, password string, hash string)) *MockPasswordService_CheckHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPasswordService_CheckHash_Call) Return(b bool, err error) *MockPasswordService_CheckHash_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPasswordService_CheckHash_Call) RunAndReturn(run func(ctx context.Context, password string, hash string) (bool, error)) *MockPasswordService_CheckHash_Call {
	_c.Call.Return(run)
	return _c
}

// CreateHash provides a mock function for the type MockPasswordService
func (_mock *MockPasswordService) CreateHash(ctx context.Context, password string) (string, error) {
	ret := _mock.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateHash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordService_CreateHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHash'
type MockPasswordService_CreateHash_Call struct {
	*mock.Call
}

// CreateHash is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
func (_e *MockPasswordService_Expecter) CreateHash(ctx interface{}, password interface{}) *MockPasswordService_CreateHash_Call {
	return &MockPasswordService_CreateHash_Call{Call: _e.mock.On("CreateHash", ctx, password)}
}

func (_c *MockPasswordService_CreateHash_Call) Run(run func(ctx context.Context, password string)) *MockPasswordService_CreateHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordService_CreateHash_Call) Return(s string, err error) *MockPasswordService_CreateHash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordService_CreateHash_Call) RunAndReturn(run func(ctx context.Context, password string) (string, error)) *MockPasswordService_CreateHash_Call {
	_c.Call.Return(run)
	return _c
}
