// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserOrderProvider creates a new instance of MockUserOrderProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserOrderProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserOrderProvider {
	mock := &MockUserOrderProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserOrderProvider is an autogenerated mock type for the UserOrderProvider type
type MockUserOrderProvider struct {
	mock.Mock
}

type MockUserOrderProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserOrderProvider) EXPECT() *MockUserOrderProvider_Expecter {
	return &MockUserOrderProvider_Expecter{mock: &_m.Mock}
}

// FindUserIDByOrderID provides a mock function for the type MockUserOrderProvider
func (_mock *MockUserOrderProvider) FindUserIDByOrderID(ctx context.Context, orderID string) (*uuid.UUID, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserIDByOrderID")
	}

	var r0 *uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*uuid.UUID, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *uuid.UUID); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserOrderProvider_FindUserIDByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserIDByOrderID'
type MockUserOrderProvider_FindUserIDByOrderID_Call struct {
	*mock.Call
}

// FindUserIDByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockUserOrderProvider_Expecter) FindUserIDByOrderID(ctx interface{}, orderID interface{}) *MockUserOrderProvider_FindUserIDByOrderID_Call {
	return &MockUserOrderProvider_FindUserIDByOrderID_Call{Call: _e.mock.On("FindUserIDByOrderID", ctx, orderID)}
}

func (_c *MockUserOrderProvider_FindUserIDByOrderID_Call) Run(run func(ctx context.Context, orderID string)) *MockUserOrderProvider_FindUserIDByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserOrderProvider_FindUserIDByOrderID_Call) Return(uUID *uuid.UUID, err error) *MockUserOrderProvider_FindUserIDByOrderID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockUserOrderProvider_FindUserIDByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*uuid.UUID, error)) *MockUserOrderProvider_FindUserIDByOrderID_Call {
	_c.Call.Return(run)
	return _c
}
