// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/liebeSonne/gophermart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// FindByLogin provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) FindByLogin(ctx context.Context, login string) (*model.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for FindByLogin")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_FindByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLogin'
type MockUserProvider_FindByLogin_Call struct {
	*mock.Call
}

// FindByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockUserProvider_Expecter) FindByLogin(ctx interface{}, login interface{}) *MockUserProvider_FindByLogin_Call {
	return &MockUserProvider_FindByLogin_Call{Call: _e.mock.On("FindByLogin", ctx, login)}
}

func (_c *MockUserProvider_FindByLogin_Call) Run(run func(ctx context.Context, login string)) *MockUserProvider_FindByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_FindByLogin_Call) Return(user *model.User, err error) *MockUserProvider_FindByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserProvider_FindByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (*model.User, error)) *MockUserProvider_FindByLogin_Call {
	_c.Call.Return(run)
	return _c
}
