// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUnitOfWorkFactory creates a new instance of MockUnitOfWorkFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWorkFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWorkFactory {
	mock := &MockUnitOfWorkFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWorkFactory is an autogenerated mock type for the UnitOfWorkFactory type
type MockUnitOfWorkFactory struct {
	mock.Mock
}

type MockUnitOfWorkFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWorkFactory) EXPECT() *MockUnitOfWorkFactory_Expecter {
	return &MockUnitOfWorkFactory_Expecter{mock: &_m.Mock}
}

// ExecuteWithUnitOfWork provides a mock function for the type MockUnitOfWorkFactory
func (_mock *MockUnitOfWorkFactory) ExecuteWithUnitOfWork(ctx context.Context, lockNames []string, fn func(provider RepositoryProvider) error) error {
	ret := _mock.Called(ctx, lockNames, fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteWithUnitOfWork")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, func(provider RepositoryProvider) error) error); ok {
		r0 = returnFunc(ctx, lockNames, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWorkFactory_ExecuteWithUnitOfWork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteWithUnitOfWork'
type MockUnitOfWorkFactory_ExecuteWithUnitOfWork_Call struct {
	*mock.Call
}

// ExecuteWithUnitOfWork is a helper method to define mock.On call
//   - ctx context.Context
//   - lockNames []string
//   - fn func(provider RepositoryProvider) error
func (_e *MockUnitOfWorkFactory_Expecter) ExecuteWithUnitOfWork(ctx interface{}, lockNames interface{}, fn interface{}) *MockUnitOfWorkFactory_ExecuteWithUnitOfWork_Call {
	return &MockUnitOfWorkFactory_ExecuteWithUnitOfWork_Call{Call: _e.mock.On("ExecuteWithUnitOfWork", ctx, lockNames, fn)}
}

func (_c *MockUnitOfWorkFactory_ExecuteWithUnitOfWork_Call) Run(run func(ctx context.Context, lockNames []string, fn func(provider RepositoryProvider) error)) *MockUnitOfWorkFactory_ExecuteWithUnitOfWork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 func(provider RepositoryProvider) error
		if args[2] != nil {
			arg2 = args[2].(func(provider RepositoryProvider) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUnitOfWorkFactory_ExecuteWithUnitOfWork_Call) Return(err error) *MockUnitOfWorkFactory_ExecuteWithUnitOfWork_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWorkFactory_ExecuteWithUnitOfWork_Call) RunAndReturn(run func(ctx context.Context, lockNames []string, fn func(provider RepositoryProvider) error) error) *MockUnitOfWorkFactory_ExecuteWithUnitOfWork_Call {
	_c.Call.Return(run)
	return _c
}
