// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutedUserOrderProvider creates a new instance of MockExecutedUserOrderProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutedUserOrderProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutedUserOrderProvider {
	mock := &MockExecutedUserOrderProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutedUserOrderProvider is an autogenerated mock type for the ExecutedUserOrderProvider type
type MockExecutedUserOrderProvider struct {
	mock.Mock
}

type MockExecutedUserOrderProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutedUserOrderProvider) EXPECT() *MockExecutedUserOrderProvider_Expecter {
	return &MockExecutedUserOrderProvider_Expecter{mock: &_m.Mock}
}

// FindOrderIDToExecuteAtMap provides a mock function for the type MockExecutedUserOrderProvider
func (_mock *MockExecutedUserOrderProvider) FindOrderIDToExecuteAtMap(ctx context.Context, spec FindUserOrderSpecification) (map[string]time.Time, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindOrderIDToExecuteAtMap")
	}

	var r0 map[string]time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, FindUserOrderSpecification) (map[string]time.Time, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, FindUserOrderSpecification) map[string]time.Time); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]time.Time)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, FindUserOrderSpecification) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutedUserOrderProvider_FindOrderIDToExecuteAtMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrderIDToExecuteAtMap'
type MockExecutedUserOrderProvider_FindOrderIDToExecuteAtMap_Call struct {
	*mock.Call
}

// FindOrderIDToExecuteAtMap is a helper method to define mock.On call
//   - ctx context.Context
//   - spec FindUserOrderSpecification
func (_e *MockExecutedUserOrderProvider_Expecter) FindOrderIDToExecuteAtMap(ctx interface{}, spec interface{}) *MockExecutedUserOrderProvider_FindOrderIDToExecuteAtMap_Call {
	return &MockExecutedUserOrderProvider_FindOrderIDToExecuteAtMap_Call{Call: _e.mock.On("FindOrderIDToExecuteAtMap", ctx, spec)}
}

func (_c *MockExecutedUserOrderProvider_FindOrderIDToExecuteAtMap_Call) Run(run func(ctx context.Context, spec FindUserOrderSpecification)) *MockExecutedUserOrderProvider_FindOrderIDToExecuteAtMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 FindUserOrderSpecification
		if args[1] != nil {
			arg1 = args[1].(FindUserOrderSpecification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExecutedUserOrderProvider_FindOrderIDToExecuteAtMap_Call) Return(stringToTime map[string]time.Time, err error) *MockExecutedUserOrderProvider_FindOrderIDToExecuteAtMap_Call {
	_c.Call.Return(stringToTime, err)
	return _c
}

func (_c *MockExecutedUserOrderProvider_FindOrderIDToExecuteAtMap_Call) RunAndReturn(run func(ctx context.Context, spec FindUserOrderSpecification) (map[string]time.Time, error)) *MockExecutedUserOrderProvider_FindOrderIDToExecuteAtMap_Call {
	_c.Call.Return(run)
	return _c
}
