// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophermart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserBalanceWithdrawnRepository creates a new instance of MockUserBalanceWithdrawnRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserBalanceWithdrawnRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserBalanceWithdrawnRepository {
	mock := &MockUserBalanceWithdrawnRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserBalanceWithdrawnRepository is an autogenerated mock type for the UserBalanceWithdrawnRepository type
type MockUserBalanceWithdrawnRepository struct {
	mock.Mock
}

type MockUserBalanceWithdrawnRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserBalanceWithdrawnRepository) EXPECT() *MockUserBalanceWithdrawnRepository_Expecter {
	return &MockUserBalanceWithdrawnRepository_Expecter{mock: &_m.Mock}
}

// NextID provides a mock function for the type MockUserBalanceWithdrawnRepository
func (_mock *MockUserBalanceWithdrawnRepository) NextID(ctx context.Context) uuid.UUID {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NextID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockUserBalanceWithdrawnRepository_NextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextID'
type MockUserBalanceWithdrawnRepository_NextID_Call struct {
	*mock.Call
}

// NextID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserBalanceWithdrawnRepository_Expecter) NextID(ctx interface{}) *MockUserBalanceWithdrawnRepository_NextID_Call {
	return &MockUserBalanceWithdrawnRepository_NextID_Call{Call: _e.mock.On("NextID", ctx)}
}

func (_c *MockUserBalanceWithdrawnRepository_NextID_Call) Run(run func(ctx context.Context)) *MockUserBalanceWithdrawnRepository_NextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserBalanceWithdrawnRepository_NextID_Call) Return(uUID uuid.UUID) *MockUserBalanceWithdrawnRepository_NextID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockUserBalanceWithdrawnRepository_NextID_Call) RunAndReturn(run func(ctx context.Context) uuid.UUID) *MockUserBalanceWithdrawnRepository_NextID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockUserBalanceWithdrawnRepository
func (_mock *MockUserBalanceWithdrawnRepository) Store(ctx context.Context, item model.UserBalanceWithdrawn) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserBalanceWithdrawn) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserBalanceWithdrawnRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockUserBalanceWithdrawnRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - item model.UserBalanceWithdrawn
func (_e *MockUserBalanceWithdrawnRepository_Expecter) Store(ctx interface{}, item interface{}) *MockUserBalanceWithdrawnRepository_Store_Call {
	return &MockUserBalanceWithdrawnRepository_Store_Call{Call: _e.mock.On("Store", ctx, item)}
}

func (_c *MockUserBalanceWithdrawnRepository_Store_Call) Run(run func(ctx context.Context, item model.UserBalanceWithdrawn)) *MockUserBalanceWithdrawnRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserBalanceWithdrawn
		if args[1] != nil {
			arg1 = args[1].(model.UserBalanceWithdrawn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserBalanceWithdrawnRepository_Store_Call) Return(err error) *MockUserBalanceWithdrawnRepository_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserBalanceWithdrawnRepository_Store_Call) RunAndReturn(run func(ctx context.Context, item model.UserBalanceWithdrawn) error) *MockUserBalanceWithdrawnRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}
