// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryProvider creates a new instance of MockRepositoryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryProvider {
	mock := &MockRepositoryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryProvider is an autogenerated mock type for the RepositoryProvider type
type MockRepositoryProvider struct {
	mock.Mock
}

type MockRepositoryProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryProvider) EXPECT() *MockRepositoryProvider_Expecter {
	return &MockRepositoryProvider_Expecter{mock: &_m.Mock}
}

// UserBalanceRepository provides a mock function for the type MockRepositoryProvider
func (_mock *MockRepositoryProvider) UserBalanceRepository() UserBalanceRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceRepository")
	}

	var r0 UserBalanceRepository
	if returnFunc, ok := ret.Get(0).(func() UserBalanceRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(UserBalanceRepository)
		}
	}
	return r0
}

// MockRepositoryProvider_UserBalanceRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserBalanceRepository'
type MockRepositoryProvider_UserBalanceRepository_Call struct {
	*mock.Call
}

// UserBalanceRepository is a helper method to define mock.On call
func (_e *MockRepositoryProvider_Expecter) UserBalanceRepository() *MockRepositoryProvider_UserBalanceRepository_Call {
	return &MockRepositoryProvider_UserBalanceRepository_Call{Call: _e.mock.On("UserBalanceRepository")}
}

func (_c *MockRepositoryProvider_UserBalanceRepository_Call) Run(run func()) *MockRepositoryProvider_UserBalanceRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryProvider_UserBalanceRepository_Call) Return(userBalanceRepository UserBalanceRepository) *MockRepositoryProvider_UserBalanceRepository_Call {
	_c.Call.Return(userBalanceRepository)
	return _c
}

func (_c *MockRepositoryProvider_UserBalanceRepository_Call) RunAndReturn(run func() UserBalanceRepository) *MockRepositoryProvider_UserBalanceRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UserBalanceWithdrawnRepository provides a mock function for the type MockRepositoryProvider
func (_mock *MockRepositoryProvider) UserBalanceWithdrawnRepository() UserBalanceWithdrawnRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceWithdrawnRepository")
	}

	var r0 UserBalanceWithdrawnRepository
	if returnFunc, ok := ret.Get(0).(func() UserBalanceWithdrawnRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(UserBalanceWithdrawnRepository)
		}
	}
	return r0
}

// MockRepositoryProvider_UserBalanceWithdrawnRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserBalanceWithdrawnRepository'
type MockRepositoryProvider_UserBalanceWithdrawnRepository_Call struct {
	*mock.Call
}

// UserBalanceWithdrawnRepository is a helper method to define mock.On call
func (_e *MockRepositoryProvider_Expecter) UserBalanceWithdrawnRepository() *MockRepositoryProvider_UserBalanceWithdrawnRepository_Call {
	return &MockRepositoryProvider_UserBalanceWithdrawnRepository_Call{Call: _e.mock.On("UserBalanceWithdrawnRepository")}
}

func (_c *MockRepositoryProvider_UserBalanceWithdrawnRepository_Call) Run(run func()) *MockRepositoryProvider_UserBalanceWithdrawnRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryProvider_UserBalanceWithdrawnRepository_Call) Return(userBalanceWithdrawnRepository UserBalanceWithdrawnRepository) *MockRepositoryProvider_UserBalanceWithdrawnRepository_Call {
	_c.Call.Return(userBalanceWithdrawnRepository)
	return _c
}

func (_c *MockRepositoryProvider_UserBalanceWithdrawnRepository_Call) RunAndReturn(run func() UserBalanceWithdrawnRepository) *MockRepositoryProvider_UserBalanceWithdrawnRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UserOrderRepository provides a mock function for the type MockRepositoryProvider
func (_mock *MockRepositoryProvider) UserOrderRepository() UserOrderRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserOrderRepository")
	}

	var r0 UserOrderRepository
	if returnFunc, ok := ret.Get(0).(func() UserOrderRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(UserOrderRepository)
		}
	}
	return r0
}

// MockRepositoryProvider_UserOrderRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserOrderRepository'
type MockRepositoryProvider_UserOrderRepository_Call struct {
	*mock.Call
}

// UserOrderRepository is a helper method to define mock.On call
func (_e *MockRepositoryProvider_Expecter) UserOrderRepository() *MockRepositoryProvider_UserOrderRepository_Call {
	return &MockRepositoryProvider_UserOrderRepository_Call{Call: _e.mock.On("UserOrderRepository")}
}

func (_c *MockRepositoryProvider_UserOrderRepository_Call) Run(run func()) *MockRepositoryProvider_UserOrderRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryProvider_UserOrderRepository_Call) Return(userOrderRepository UserOrderRepository) *MockRepositoryProvider_UserOrderRepository_Call {
	_c.Call.Return(userOrderRepository)
	return _c
}

func (_c *MockRepositoryProvider_UserOrderRepository_Call) RunAndReturn(run func() UserOrderRepository) *MockRepositoryProvider_UserOrderRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepository provides a mock function for the type MockRepositoryProvider
func (_mock *MockRepositoryProvider) UserRepository() UserRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepository")
	}

	var r0 UserRepository
	if returnFunc, ok := ret.Get(0).(func() UserRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(UserRepository)
		}
	}
	return r0
}

// MockRepositoryProvider_UserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepository'
type MockRepositoryProvider_UserRepository_Call struct {
	*mock.Call
}

// UserRepository is a helper method to define mock.On call
func (_e *MockRepositoryProvider_Expecter) UserRepository() *MockRepositoryProvider_UserRepository_Call {
	return &MockRepositoryProvider_UserRepository_Call{Call: _e.mock.On("UserRepository")}
}

func (_c *MockRepositoryProvider_UserRepository_Call) Run(run func()) *MockRepositoryProvider_UserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryProvider_UserRepository_Call) Return(userRepository UserRepository) *MockRepositoryProvider_UserRepository_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *MockRepositoryProvider_UserRepository_Call) RunAndReturn(run func() UserRepository) *MockRepositoryProvider_UserRepository_Call {
	_c.Call.Return(run)
	return _c
}
