// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package async

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer[T] {
	mock := &MockProducer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer[T any] struct {
	mock.Mock
}

type MockProducer_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockProducer[T]) EXPECT() *MockProducer_Expecter[T] {
	return &MockProducer_Expecter[T]{mock: &_m.Mock}
}

// Add provides a mock function for the type MockProducer
func (_mock *MockProducer[T]) Add(value T) {
	_mock.Called(value)
	return
}

// MockProducer_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockProducer_Add_Call[T any] struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - value T
func (_e *MockProducer_Expecter[T]) Add(value interface{}) *MockProducer_Add_Call[T] {
	return &MockProducer_Add_Call[T]{Call: _e.mock.On("Add", value)}
}

func (_c *MockProducer_Add_Call[T]) Run(run func(value T)) *MockProducer_Add_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProducer_Add_Call[T]) Return() *MockProducer_Add_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockProducer_Add_Call[T]) RunAndReturn(run func(value T)) *MockProducer_Add_Call[T] {
	_c.Run(run)
	return _c
}

// Produce provides a mock function for the type MockProducer
func (_mock *MockProducer[T]) Produce() <-chan T {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 <-chan T
	if returnFunc, ok := ret.Get(0).(func() <-chan T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan T)
		}
	}
	return r0
}

// MockProducer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type MockProducer_Produce_Call[T any] struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
func (_e *MockProducer_Expecter[T]) Produce() *MockProducer_Produce_Call[T] {
	return &MockProducer_Produce_Call[T]{Call: _e.mock.On("Produce")}
}

func (_c *MockProducer_Produce_Call[T]) Run(run func()) *MockProducer_Produce_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProducer_Produce_Call[T]) Return(vCh <-chan T) *MockProducer_Produce_Call[T] {
	_c.Call.Return(vCh)
	return _c
}

func (_c *MockProducer_Produce_Call[T]) RunAndReturn(run func() <-chan T) *MockProducer_Produce_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Schedule provides a mock function for the type MockProducer
func (_mock *MockProducer[T]) Schedule(value T, delay time.Duration) CancelFunc {
	ret := _mock.Called(value, delay)

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 CancelFunc
	if returnFunc, ok := ret.Get(0).(func(T, time.Duration) CancelFunc); ok {
		r0 = returnFunc(value, delay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CancelFunc)
		}
	}
	return r0
}

// MockProducer_Schedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schedule'
type MockProducer_Schedule_Call[T any] struct {
	*mock.Call
}

// Schedule is a helper method to define mock.On call
//   - value T
//   - delay time.Duration
func (_e *MockProducer_Expecter[T]) Schedule(value interface{}, delay interface{}) *MockProducer_Schedule_Call[T] {
	return &MockProducer_Schedule_Call[T]{Call: _e.mock.On("Schedule", value, delay)}
}

func (_c *MockProducer_Schedule_Call[T]) Run(run func(value T, delay time.Duration)) *MockProducer_Schedule_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProducer_Schedule_Call[T]) Return(cancelFunc CancelFunc) *MockProducer_Schedule_Call[T] {
	_c.Call.Return(cancelFunc)
	return _c
}

func (_c *MockProducer_Schedule_Call[T]) RunAndReturn(run func(value T, delay time.Duration) CancelFunc) *MockProducer_Schedule_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Setup provides a mock function for the type MockProducer
func (_mock *MockProducer[T]) Setup(inputCh <-chan T) CancelFunc {
	ret := _mock.Called(inputCh)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 CancelFunc
	if returnFunc, ok := ret.Get(0).(func(<-chan T) CancelFunc); ok {
		r0 = returnFunc(inputCh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CancelFunc)
		}
	}
	return r0
}

// MockProducer_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockProducer_Setup_Call[T any] struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - inputCh <-chan T
func (_e *MockProducer_Expecter[T]) Setup(inputCh interface{}) *MockProducer_Setup_Call[T] {
	return &MockProducer_Setup_Call[T]{Call: _e.mock.On("Setup", inputCh)}
}

func (_c *MockProducer_Setup_Call[T]) Run(run func(inputCh <-chan T)) *MockProducer_Setup_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 <-chan T
		if args[0] != nil {
			arg0 = args[0].(<-chan T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProducer_Setup_Call[T]) Return(cancelFunc CancelFunc) *MockProducer_Setup_Call[T] {
	_c.Call.Return(cancelFunc)
	return _c
}

func (_c *MockProducer_Setup_Call[T]) RunAndReturn(run func(inputCh <-chan T) CancelFunc) *MockProducer_Setup_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockProducer
func (_mock *MockProducer[T]) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockProducer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockProducer_Start_Call[T any] struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProducer_Expecter[T]) Start(ctx interface{}) *MockProducer_Start_Call[T] {
	return &MockProducer_Start_Call[T]{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockProducer_Start_Call[T]) Run(run func(ctx context.Context)) *MockProducer_Start_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProducer_Start_Call[T]) Return() *MockProducer_Start_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockProducer_Start_Call[T]) RunAndReturn(run func(ctx context.Context)) *MockProducer_Start_Call[T] {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockProducer
func (_mock *MockProducer[T]) Stop() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProducer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockProducer_Stop_Call[T any] struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockProducer_Expecter[T]) Stop() *MockProducer_Stop_Call[T] {
	return &MockProducer_Stop_Call[T]{Call: _e.mock.On("Stop")}
}

func (_c *MockProducer_Stop_Call[T]) Run(run func()) *MockProducer_Stop_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProducer_Stop_Call[T]) Return(b bool) *MockProducer_Stop_Call[T] {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProducer_Stop_Call[T]) RunAndReturn(run func() bool) *MockProducer_Stop_Call[T] {
	_c.Call.Return(run)
	return _c
}
