// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package uow

import (
	"github.com/liebeSonne/gophermart/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryProvider creates a new instance of MockRepositoryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryProvider {
	mock := &MockRepositoryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryProvider is an autogenerated mock type for the RepositoryProvider type
type MockRepositoryProvider struct {
	mock.Mock
}

type MockRepositoryProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryProvider) EXPECT() *MockRepositoryProvider_Expecter {
	return &MockRepositoryProvider_Expecter{mock: &_m.Mock}
}

// UserOrderRepository provides a mock function for the type MockRepositoryProvider
func (_mock *MockRepositoryProvider) UserOrderRepository() repository.UserOrderRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserOrderRepository")
	}

	var r0 repository.UserOrderRepository
	if returnFunc, ok := ret.Get(0).(func() repository.UserOrderRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserOrderRepository)
		}
	}
	return r0
}

// MockRepositoryProvider_UserOrderRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserOrderRepository'
type MockRepositoryProvider_UserOrderRepository_Call struct {
	*mock.Call
}

// UserOrderRepository is a helper method to define mock.On call
func (_e *MockRepositoryProvider_Expecter) UserOrderRepository() *MockRepositoryProvider_UserOrderRepository_Call {
	return &MockRepositoryProvider_UserOrderRepository_Call{Call: _e.mock.On("UserOrderRepository")}
}

func (_c *MockRepositoryProvider_UserOrderRepository_Call) Run(run func()) *MockRepositoryProvider_UserOrderRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryProvider_UserOrderRepository_Call) Return(userOrderRepository repository.UserOrderRepository) *MockRepositoryProvider_UserOrderRepository_Call {
	_c.Call.Return(userOrderRepository)
	return _c
}

func (_c *MockRepositoryProvider_UserOrderRepository_Call) RunAndReturn(run func() repository.UserOrderRepository) *MockRepositoryProvider_UserOrderRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepository provides a mock function for the type MockRepositoryProvider
func (_mock *MockRepositoryProvider) UserRepository() repository.UserRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepository")
	}

	var r0 repository.UserRepository
	if returnFunc, ok := ret.Get(0).(func() repository.UserRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserRepository)
		}
	}
	return r0
}

// MockRepositoryProvider_UserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepository'
type MockRepositoryProvider_UserRepository_Call struct {
	*mock.Call
}

// UserRepository is a helper method to define mock.On call
func (_e *MockRepositoryProvider_Expecter) UserRepository() *MockRepositoryProvider_UserRepository_Call {
	return &MockRepositoryProvider_UserRepository_Call{Call: _e.mock.On("UserRepository")}
}

func (_c *MockRepositoryProvider_UserRepository_Call) Run(run func()) *MockRepositoryProvider_UserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryProvider_UserRepository_Call) Return(userRepository repository.UserRepository) *MockRepositoryProvider_UserRepository_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *MockRepositoryProvider_UserRepository_Call) RunAndReturn(run func() repository.UserRepository) *MockRepositoryProvider_UserRepository_Call {
	_c.Call.Return(run)
	return _c
}
