// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for UserOrderDataStatus.
const (
	INVALID    UserOrderDataStatus = "INVALID"
	NEW        UserOrderDataStatus = "NEW"
	PROCESSED  UserOrderDataStatus = "PROCESSED"
	PROCESSING UserOrderDataStatus = "PROCESSING"
)

// Valid indicates whether the value is a known member of the UserOrderDataStatus enum.
func (e UserOrderDataStatus) Valid() bool {
	switch e {
	case INVALID:
		return true
	case NEW:
		return true
	case PROCESSED:
		return true
	case PROCESSING:
		return true
	default:
		return false
	}
}

// GetUserBalanceResponse defines model for GetUserBalanceResponse.
type GetUserBalanceResponse struct {
	// Current текущая сумма баллов лояльности
	Current float32 `json:"current"`

	// Withdrawn сумма использованных за весь период регистрации баллов
	Withdrawn float32 `json:"withdrawn"`
}

// GetUserOrdersResponse defines model for GetUserOrdersResponse.
type GetUserOrdersResponse = []UserOrderData

// GetUserWithdrawalsResponse defines model for GetUserWithdrawalsResponse.
type GetUserWithdrawalsResponse = []WithdrawalData

// OrderId номер заказа, последовательность цифр произвольной длины
type OrderId = string

// UserCredentials defines model for UserCredentials.
type UserCredentials struct {
	// Login уникальное имя пользователя
	Login    string `json:"login"`
	Password string `json:"password"`
}

// UserOrderData defines model for UserOrderData.
type UserOrderData struct {
	// Accrual начисленные баллы, при отсутствии начисления (status не равен PROCESSED) - поле отсутствует в ответе
	Accrual *float32 `json:"accrual,omitempty"`

	// Number номер заказа, последовательность цифр произвольной длины
	Number OrderId `json:"number"`

	// Status статус обработки расчётов
	Status UserOrderDataStatus `json:"status"`

	// UploadedAt дата и время загрузки заказа, в формате RFC3339
	UploadedAt time.Time `json:"uploaded_at"`
}

// UserOrderDataStatus статус обработки расчётов
type UserOrderDataStatus string

// WithdrawUserBalanceRequest defines model for WithdrawUserBalanceRequest.
type WithdrawUserBalanceRequest struct {
	// Order номер заказа, последовательность цифр произвольной длины
	Order OrderId `json:"order"`
	Sum   float32 `json:"sum"`
}

// WithdrawalData defines model for WithdrawalData.
type WithdrawalData struct {
	// Order номер заказа, последовательность цифр произвольной длины
	Order OrderId `json:"order"`

	// ProcessedAt дата и время списания, в формате RFC3339
	ProcessedAt time.Time `json:"processed_at"`
	Sum         float32   `json:"sum"`
}

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// WithdrawUserBalanceJSONRequestBody defines body for WithdrawUserBalance for application/json ContentType.
type WithdrawUserBalanceJSONRequestBody = WithdrawUserBalanceRequest

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = UserCredentials

// UploadUserOrdersTextRequestBody defines body for UploadUserOrders for text/plain ContentType.
type UploadUserOrdersTextRequestBody = OrderId

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = UserCredentials

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение текущего баланса пользователя
	// (GET /api/user/balance)
	GetUserBalance(w http.ResponseWriter, r *http.Request)
	// Запрос на списание средств
	// (POST /api/user/balance/withdraw)
	WithdrawUserBalance(w http.ResponseWriter, r *http.Request)
	// Аутентификация пользователя
	// (POST /api/user/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Получение списка загруженных номеров заказов
	// (GET /api/user/orders)
	GetUserOrders(w http.ResponseWriter, r *http.Request)
	// Загрузка номена заказа
	// (POST /api/user/orders)
	UploadUserOrders(w http.ResponseWriter, r *http.Request)
	// Регистрация пользователя
	// (POST /api/user/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Получение информации о выводе средств
	// (GET /api/user/withdrawals)
	GetUserWithdrawals(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Получение текущего баланса пользователя
// (GET /api/user/balance)
func (_ Unimplemented) GetUserBalance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Запрос на списание средств
// (POST /api/user/balance/withdraw)
func (_ Unimplemented) WithdrawUserBalance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Аутентификация пользователя
// (POST /api/user/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение списка загруженных номеров заказов
// (GET /api/user/orders)
func (_ Unimplemented) GetUserOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Загрузка номена заказа
// (POST /api/user/orders)
func (_ Unimplemented) UploadUserOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Регистрация пользователя
// (POST /api/user/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение информации о выводе средств
// (GET /api/user/withdrawals)
func (_ Unimplemented) GetUserWithdrawals(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetUserBalance operation middleware
func (siw *ServerInterfaceWrapper) GetUserBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WithdrawUserBalance operation middleware
func (siw *ServerInterfaceWrapper) WithdrawUserBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WithdrawUserBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserOrders operation middleware
func (siw *ServerInterfaceWrapper) GetUserOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadUserOrders operation middleware
func (siw *ServerInterfaceWrapper) UploadUserOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserWithdrawals operation middleware
func (siw *ServerInterfaceWrapper) GetUserWithdrawals(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserWithdrawals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/balance", wrapper.GetUserBalance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/balance/withdraw", wrapper.WithdrawUserBalance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/orders", wrapper.GetUserOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/orders", wrapper.UploadUserOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/withdrawals", wrapper.GetUserWithdrawals)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Flfb9vIEf8qxLYPLSpHlGz1EgV5yCVpzmiQBHGv92AYh7W0sXgn/slydYkRCLDltL4iKdQ+9bH9CLQi",
	"1brYUr7C7DcqZpaiSIqy45zjIvfgPyK5y5n5/Wbmt6OXrOG7ge8JT4Ws/pK1BG8KSf9uCHW7o1p3fP97",
	"R3xF1/FyU4QN6QTK8T1WZ/pA7+seRDCBCAZwAmMYQAQj3bPgnT7AHwvv6B5M9R6M4Rgi/VcYw5iVWNho",
	"CZfjpuIFd4O2YHXGGw0Rht8q/3vh3eLbjUp19ab1mKvWrfJN6yulgkdee/emtSEaHSluWhvcFRuOErc2",
	"lHQaipWY2g1wn1BJx9th3W539h5y6r5QX4dCfsnb3GuIJyIMfC8UeCeQfiCkcgQ91+hIKTxV4HAPRuiV",
	"/htEum/pfX0Ap3AKkQVHEMEJnMAUBhb+0X040W9gAlOKEXo897Nm29dqrMSe+tLlitXZ07bPU/Z7HXdb",
	"SNYtseeOajUlf+4VGJN6+1jvw3uY0iuP0QYCZaJf679YGHULBjDS+/qNBe9hRFhMYWjpPRjBW1yte3pv",
	"Bk7GmYzda9VrdpHZruM5bsdldXvBhW6JSfGs40jRZPXNJLRpz7aSRf72d6Kh0O8YqkcSCZlGylHCJZB+",
	"LcVTVme/Ks85XI6xLidL73LFcbt4fy4l301t/01sA29f/B3ztcteQhasNxeRQ1bAKeJA4MA7iPBvCcGZ",
	"6n04gREMDYrEuBSR9BsLQdKvcO17vQdTSqtBjD1u/JMFQ8rFiX6dQa9SXV2r/f6L6zfsVYPZA+HtqBar",
	"VxYSp8QwPHekaApPObwdLiZJ299xilh5ABMYk0szg0YWjOFU9608RWPn+mgNfzGzplqrnWtdwMPwuS8p",
	"tgkbk4vnLM9R0jiS2rOIj1lGLQSDNxqyw9uFUEf6kPITUaWcxIDEGaZflwyMYwumuocpTb97MDCZmF8+",
	"1n3rN6HiqhPizRGmMNbeEUysx08e3bm3sXHv7m+tlTjW+KrcvvrAFOgB3aG60INRlihYni6a6KXZf+fk",
	"zSwrsDSTH4WVrYfswP5iwRSOyMkjsvcdjMlnva8P9T+xs5ga5aFVm+zhvW9YicWRWH94n5XY+sM/336w",
	"fnd++d7dFMRzTnWCts+bovktL6j8MCS6Yqm1YEB1kxiN6ftW7+kDOCbTcvk8sPQr6n2nhu3Wkz/cWV1d",
	"vZEJd9Wu2iuV6krF/lOlVq/U6mu139mrdTuDQJMrsaIcV7Dz+BzDkIQ361kRuWelLNMcn3VEqBaZ7svm",
	"xTBGXNI9/ota5ec2EWOD2fssf+LS/LN9CKSPuuRi1KCOjIkbmbS9KjYUhBzlxiWGPBeQRQTQBpRojtrd",
	"wGjGqoq0JKpK6rEYOnOJlZjH3bz+m3vGA+ePYteoOcd76uNy5Shy7b4ftIR0uVRW0NluOw3r9uN1VmI/",
	"CBkaeCrX0PluifmB8HjgsDpbvWbiEXDVItPKPHDKnVDI8rahP17cEQQ2Eocj1NjJcxKSYZCMbqB9qrZt",
	"PPVUrB95ELSdBq0vfxf61DDnyvcs/i0RqxSFRRlOsu5Hahf9xZIZmbpEegEZieFYsysFXC7u0G9Mr8lp",
	"+Vhm4mY143huswFMqO/sxZ2vT7bpH2EMR2SV3icxOqDfkSFOx3W53MXl/yZbDvSh6XzY7Ob6G3XrdNZH",
	"I5igW2cJDMV3QiTys46Qu2wLX7WAenmmSalk+GEB/gWlkplMEaH60m/uXhr+ZxTlbjY7leyIbjETL4co",
	"dqGuGcW4oaL5KVPZPjXb1uxqsdLCE9khCho8eE6Mip6JCZjqQ5Sj+AwScmjkEO1XrX6Ah0tU+yej/7/m",
	"MbRi59IdBdMh68mc5A3fdbnXzNM8kezF3H6At5Fun4jR+SPFx9J4KW0y/J5aEGH4Mfh4ANevYExHp72E",
	"SqXcxGPFjDuW+RE/XC6ajZAvnzBTUpuYzH0PEZKGZg14hIdJOb5GsblkVsbdnNU3tzIc/Uc+wrgDRbn/",
	"IcWYoxjIkZSURnheAzaDgSvov7kJxKW136q9VgwzkmKYHt8MMWjpw9rn275nBSwJiTk6/Xd2MkZ3kypr",
	"RmnzSjvNlLhZHy8tKWZf05knR5VlNU2JF6octLlzAX4k54OPrWLF7cQy8bDgSL+Gk4UoWfrvmGpwuiS9",
	"8PBh6FVd8srBWc0sHkYQ2PGMIMtlffD/lQTnVHTa9salBRuG9OHtBwT8wzRENiRzqkdXJynm04oosYDk",
	"RcaCc7WEFDtOqMwxujgDn8RP/JIUxTF12PTMPMU+GgB8ppqjKGcSZZGkyTGdtPq6d0Xy4j+LX098vLB4",
	"Ph/2n6cuUt8LXIHEKPoW4mp0xoTmzjCkOvCWzkbZodXnqjSohc05H3+tNbWo+w3I5TOOT8mMIMvN7Ahr",
	"c6uLZBXyB0rmzZesI9uszlpKBfVyue03eLvlh6p+3b5uM3w23v5lMu3Cfbql5POs0qYuGUu6W93/BQAA",
	"//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
