// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for UserOrderDataStatus.
const (
	INVALID    UserOrderDataStatus = "INVALID"
	NEW        UserOrderDataStatus = "NEW"
	PROCESSED  UserOrderDataStatus = "PROCESSED"
	PROCESSING UserOrderDataStatus = "PROCESSING"
)

// Valid indicates whether the value is a known member of the UserOrderDataStatus enum.
func (e UserOrderDataStatus) Valid() bool {
	switch e {
	case INVALID:
		return true
	case NEW:
		return true
	case PROCESSED:
		return true
	case PROCESSING:
		return true
	default:
		return false
	}
}

// GetUserBalanceResponse defines model for GetUserBalanceResponse.
type GetUserBalanceResponse struct {
	// Current текущая сумма баллов лояльности
	Current float64 `json:"current"`

	// Withdrawn сумма использованных за весь период регистрации баллов
	Withdrawn float64 `json:"withdrawn"`
}

// GetUserOrdersResponse defines model for GetUserOrdersResponse.
type GetUserOrdersResponse = []UserOrderData

// GetUserWithdrawalsResponse defines model for GetUserWithdrawalsResponse.
type GetUserWithdrawalsResponse = []WithdrawalData

// OrderId номер заказа, последовательность цифр произвольной длины
type OrderId = string

// UserCredentials defines model for UserCredentials.
type UserCredentials struct {
	// Login уникальное имя пользователя
	Login    string `json:"login"`
	Password string `json:"password"`
}

// UserOrderData defines model for UserOrderData.
type UserOrderData struct {
	// Accrual начисленные баллы, при отсутствии начисления (status не равен PROCESSED) - поле отсутствует в ответе
	Accrual *float64 `json:"accrual,omitempty"`

	// Number номер заказа, последовательность цифр произвольной длины
	Number OrderId `json:"number"`

	// Status статус обработки расчётов
	Status UserOrderDataStatus `json:"status"`

	// UploadedAt дата и время загрузки заказа, в формате RFC3339
	UploadedAt time.Time `json:"uploaded_at"`
}

// UserOrderDataStatus статус обработки расчётов
type UserOrderDataStatus string

// WithdrawUserBalanceRequest defines model for WithdrawUserBalanceRequest.
type WithdrawUserBalanceRequest struct {
	// Order номер заказа, последовательность цифр произвольной длины
	Order OrderId `json:"order"`
	Sum   float64 `json:"sum"`
}

// WithdrawalData defines model for WithdrawalData.
type WithdrawalData struct {
	// Order номер заказа, последовательность цифр произвольной длины
	Order OrderId `json:"order"`

	// ProcessedAt дата и время списания, в формате RFC3339
	ProcessedAt time.Time `json:"processed_at"`
	Sum         float64   `json:"sum"`
}

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// WithdrawUserBalanceJSONRequestBody defines body for WithdrawUserBalance for application/json ContentType.
type WithdrawUserBalanceJSONRequestBody = WithdrawUserBalanceRequest

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = UserCredentials

// UploadUserOrdersTextRequestBody defines body for UploadUserOrders for text/plain ContentType.
type UploadUserOrdersTextRequestBody = OrderId

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = UserCredentials

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение текущего баланса пользователя
	// (GET /api/user/balance)
	GetUserBalance(w http.ResponseWriter, r *http.Request)
	// Запрос на списание средств
	// (POST /api/user/balance/withdraw)
	WithdrawUserBalance(w http.ResponseWriter, r *http.Request)
	// Аутентификация пользователя
	// (POST /api/user/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Получение списка загруженных номеров заказов
	// (GET /api/user/orders)
	GetUserOrders(w http.ResponseWriter, r *http.Request)
	// Загрузка номена заказа
	// (POST /api/user/orders)
	UploadUserOrders(w http.ResponseWriter, r *http.Request)
	// Регистрация пользователя
	// (POST /api/user/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Получение информации о выводе средств
	// (GET /api/user/withdrawals)
	GetUserWithdrawals(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Получение текущего баланса пользователя
// (GET /api/user/balance)
func (_ Unimplemented) GetUserBalance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Запрос на списание средств
// (POST /api/user/balance/withdraw)
func (_ Unimplemented) WithdrawUserBalance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Аутентификация пользователя
// (POST /api/user/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение списка загруженных номеров заказов
// (GET /api/user/orders)
func (_ Unimplemented) GetUserOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Загрузка номена заказа
// (POST /api/user/orders)
func (_ Unimplemented) UploadUserOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Регистрация пользователя
// (POST /api/user/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение информации о выводе средств
// (GET /api/user/withdrawals)
func (_ Unimplemented) GetUserWithdrawals(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetUserBalance operation middleware
func (siw *ServerInterfaceWrapper) GetUserBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WithdrawUserBalance operation middleware
func (siw *ServerInterfaceWrapper) WithdrawUserBalance(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WithdrawUserBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserOrders operation middleware
func (siw *ServerInterfaceWrapper) GetUserOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadUserOrders operation middleware
func (siw *ServerInterfaceWrapper) UploadUserOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadUserOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserWithdrawals operation middleware
func (siw *ServerInterfaceWrapper) GetUserWithdrawals(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserWithdrawals(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/balance", wrapper.GetUserBalance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/balance/withdraw", wrapper.WithdrawUserBalance)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/orders", wrapper.GetUserOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/orders", wrapper.UploadUserOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/user/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/user/withdrawals", wrapper.GetUserWithdrawals)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Flfb9vIEf8qxLYPLSpHlGz1EgV5yCVpzmiQBHGv92AYh7W0sXgn/slyeYkRCLDltL4iKdQ+9bH9CLQi",
	"1brYUr7C7DcqZpaiRIqy45zjIvfgPyK5y5n5/Wbmt6OXrOG7ge8JT4Ws/pK1BG8KSf9uCHU7Uq07vv+9",
	"I76i63i5KcKGdALl+B6rM32g93UXYhhDDH04gRH0IYah7lrwTh/gj4V3dBcmeg9GcAyx/iuMYMRKLGy0",
	"hMtxU/GCu0FbsDrjjYYIw2+V/73wbvHtRqW6etN6zFXrVvmm9ZVSwSOvvXvT2hCNSIqb1gZ3xYajxK0N",
	"JZ2GYiWmdgPcJ1TS8XZYp9OZvoecui/U16GQX/I29xriiQgD3wsF3gmkHwipHEHPNSIphacKHO7CEL3S",
	"f4NY9yy9rw/gFE4htuAIYjiBE5hA38I/ugcn+g2MYUIxQo9nftZs+1qNldhTX7pcsTpr+tF2W8wc8CJ3",
	"W0jWKbHnjmo1JX/uFVgz9/qR3of3MKF3HqMRhMpYv9Z/sTDsFvRhqPf1Gwvew5DAmMDA0nswhLe4Wnf1",
	"3hSdjDcZw9eq1+xCu13Hc9zIZXV7wYdOiUnxLHKkaLL6Zhrcede20kX+9neiodDxBKxHEik5j5WjhEsw",
	"/VqKp6zOflWesbicoF1Ol97liuN2yf5cSr47t/03iQ28ffF3zNYuewlZsN5chA55AacIBKED7yDGvyVE",
	"Z6L34QSGMDAwEufmqKTfWIiSfoVr3+s9mFBi9RPwceOfLBhQNo716wx8lerqWu33X1y/Ya8azB4Ib0e1",
	"WL2ykDolhuG5I0VTeMrh7XAxTdr+jlNEywMYw4hcmho0tGAEp7pn5TmaONdDa/iLqTXVWu1c6wIehs99",
	"SbFN6ZhePGd5jpLGkbk9i/iYZdRCMHijISPeLoQ61oeUoIgqJSUGJEkx/bpkYBxZMNFdzGn63YW+ScX8",
	"8pHuWb8JFVdRiDeHmMNYfYcwth4/eXTn3sbGvbu/tVaSWOOrcvvqA1Oi+3SHCkMXhlmiYIG6cKaXpv+d",
	"kzjTtMDqTI4U1rYu0gNbjAUTOCIvj8jgdzAip/W+PtT/xOZiqpSHVm2yh/e+YSWWhGL94X1WYusP/3z7",
	"wfrd2eV7d+cwnpEqCto+b4rmt7yg+MOA+IrF1oI+VU6iNObvW72nD+CYTMsldN/Sr6j9nRq6W0/+cGd1",
	"dfVGJt5Vu2qvVKorFftPlVq9Uquv1X5nr9btLARciRXluIKdR+gEhjS8Wc+K2D2tZZn++CwSoVqkui+b",
	"F8MYcZlv81/UKj+7jRgjzOZnOZQU55/tRCB91CYX4wY1ZUzd2CTuVdGhIOYoOS4z5rmILEKARqBOc9Tu",
	"BoYzkVYkKFFaUpvF2JlLrMQ87uZF4Mw1Hjh/FLtG0jneUx+XK0eRb/f9oCWky6Wygmi77TSs24/XWYn9",
	"IGRo8KlcQ+87JeYHwuOBw+ps9ZoJSMBVi0wr88ApR6GQ5W2TAHhxRxDayByOWGMzz+lIhkEy0oH2qdq2",
	"8dRTiYjkQdB2GrS+/F3oU8+cyd+zCLhEsVIUFrU4SbsfqWP0FotmbCoTSQakJIZjza4UkLm4Sb8x7SYn",
	"6BOpiZvVjOO5zfowptazlzS/Htmmf4QRHJFVep8EaZ9+x4Y4ketyuYvL/022HOhD0/yw381EOGrXybSV",
	"xjBGt87SGIrvhEjkZ5GQu2wLX7WAenkqS6lm+GEB/gXFkplMEaH60m/uXhr+Z5TlTjY7lYxEp5iJl0MU",
	"u1DaDBPcUNT8lCltn5pta3a1WGzhsewQNQ2ePsdGSE/lBEz0ISpSfAYJOTCKiParVj/AwyXC/ZPR/1+z",
	"GFqJc/MtBdMh68mM5A3fdbnXzNM8Ve3F3H6At5Fun4jR+VPFx9J4KW0y/J5YEGP4Mfh4CtevYESnp72U",
	"SqXc2GPFzDyW+ZE8XC4akJAvnzBT5jYxmfseYiQNDRzwGA/jcnKNYnPJrEy6OatvbmU4+o98hHEHinLv",
	"Q4oxRzGQIykpjfC8BmxmA1fQf3NDiEtrv1V7rRhmJMVgfoQzwKDNn9c+3/Y9LWBpSMzh6b/TwzG6m1ZZ",
	"M0+bVdpJpsRN+3hpSTH7mk49Oaosq2lKvFDloM2dC/AjPSB8bBUrbieWiYcFR/o1nCxEydJ/x1SD0yXp",
	"hacPQ6/qklf2z2pmyTyCwE7GBFku64P/ryQ4p6LTtjcuLdgwoA9vPyDgH6YhsiGZUT2+Okkxm1fEqQUk",
	"LzIWnKslpNhxQmXO0cUZ+CR54pekKI6pw87PzefYRxOAz1RzFOVMqizSNDmmk1ZPd69IXvxn8SuKjxcW",
	"z2fz/vPUxdxXA1cgMYq+iLganTGm0TMMqA68pbNRdmr1uSoNamEzzidfbU0s6n59cvmM41M6I8hyMzvC",
	"2tzqIFmF/IGSefMli2Sb1VlLqaBeLrf9Bm+3/FDVr9vXbYbPJtu/TKdduE+nlH6eVtq5S8aSzlbnfwEA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
