// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package provider

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/liebeSonne/gophermart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserOrderProvider creates a new instance of MockUserOrderProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserOrderProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserOrderProvider {
	mock := &MockUserOrderProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserOrderProvider is an autogenerated mock type for the UserOrderProvider type
type MockUserOrderProvider struct {
	mock.Mock
}

type MockUserOrderProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserOrderProvider) EXPECT() *MockUserOrderProvider_Expecter {
	return &MockUserOrderProvider_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function for the type MockUserOrderProvider
func (_mock *MockUserOrderProvider) FindByUserID(ctx context.Context, userID uuid.UUID) ([]model.UserOrder, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []model.UserOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.UserOrder, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.UserOrder); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserOrderProvider_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockUserOrderProvider_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserOrderProvider_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockUserOrderProvider_FindByUserID_Call {
	return &MockUserOrderProvider_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockUserOrderProvider_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserOrderProvider_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserOrderProvider_FindByUserID_Call) Return(userOrders []model.UserOrder, err error) *MockUserOrderProvider_FindByUserID_Call {
	_c.Call.Return(userOrders, err)
	return _c
}

func (_c *MockUserOrderProvider_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]model.UserOrder, error)) *MockUserOrderProvider_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrderIDToExecuteAtMap provides a mock function for the type MockUserOrderProvider
func (_mock *MockUserOrderProvider) FindOrderIDToExecuteAtMap(ctx context.Context, spec model.FindUserOrderSpecification) (map[string]time.Time, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for FindOrderIDToExecuteAtMap")
	}

	var r0 map[string]time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindUserOrderSpecification) (map[string]time.Time, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FindUserOrderSpecification) map[string]time.Time); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]time.Time)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.FindUserOrderSpecification) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserOrderProvider_FindOrderIDToExecuteAtMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrderIDToExecuteAtMap'
type MockUserOrderProvider_FindOrderIDToExecuteAtMap_Call struct {
	*mock.Call
}

// FindOrderIDToExecuteAtMap is a helper method to define mock.On call
//   - ctx context.Context
//   - spec model.FindUserOrderSpecification
func (_e *MockUserOrderProvider_Expecter) FindOrderIDToExecuteAtMap(ctx interface{}, spec interface{}) *MockUserOrderProvider_FindOrderIDToExecuteAtMap_Call {
	return &MockUserOrderProvider_FindOrderIDToExecuteAtMap_Call{Call: _e.mock.On("FindOrderIDToExecuteAtMap", ctx, spec)}
}

func (_c *MockUserOrderProvider_FindOrderIDToExecuteAtMap_Call) Run(run func(ctx context.Context, spec model.FindUserOrderSpecification)) *MockUserOrderProvider_FindOrderIDToExecuteAtMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.FindUserOrderSpecification
		if args[1] != nil {
			arg1 = args[1].(model.FindUserOrderSpecification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserOrderProvider_FindOrderIDToExecuteAtMap_Call) Return(stringToTime map[string]time.Time, err error) *MockUserOrderProvider_FindOrderIDToExecuteAtMap_Call {
	_c.Call.Return(stringToTime, err)
	return _c
}

func (_c *MockUserOrderProvider_FindOrderIDToExecuteAtMap_Call) RunAndReturn(run func(ctx context.Context, spec model.FindUserOrderSpecification) (map[string]time.Time, error)) *MockUserOrderProvider_FindOrderIDToExecuteAtMap_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserIDByOrderID provides a mock function for the type MockUserOrderProvider
func (_mock *MockUserOrderProvider) FindUserIDByOrderID(ctx context.Context, orderID string) (*uuid.UUID, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserIDByOrderID")
	}

	var r0 *uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*uuid.UUID, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *uuid.UUID); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserOrderProvider_FindUserIDByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserIDByOrderID'
type MockUserOrderProvider_FindUserIDByOrderID_Call struct {
	*mock.Call
}

// FindUserIDByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockUserOrderProvider_Expecter) FindUserIDByOrderID(ctx interface{}, orderID interface{}) *MockUserOrderProvider_FindUserIDByOrderID_Call {
	return &MockUserOrderProvider_FindUserIDByOrderID_Call{Call: _e.mock.On("FindUserIDByOrderID", ctx, orderID)}
}

func (_c *MockUserOrderProvider_FindUserIDByOrderID_Call) Run(run func(ctx context.Context, orderID string)) *MockUserOrderProvider_FindUserIDByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserOrderProvider_FindUserIDByOrderID_Call) Return(uUID *uuid.UUID, err error) *MockUserOrderProvider_FindUserIDByOrderID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockUserOrderProvider_FindUserIDByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*uuid.UUID, error)) *MockUserOrderProvider_FindUserIDByOrderID_Call {
	_c.Call.Return(run)
	return _c
}
